### ISSUE TITLE
Cocoapods is still delivering v1.1.2

### ISSUE THREAD

**Issue by gravicle** [WorldDownTown/ZoomTransitioning#10]
Cocoapods is still dispensing v `1.1.2` of the repository instead of `1.4.0`. My workaround is to use the direct link for now:

`pod 'ZoomTransitioning', :git => 'https://github.com/WorldDownTown/ZoomTransitioning.git'`

<img width="1241" alt="screen shot 2016-12-07 at 3 57 58 pm" src="https://cloud.githubusercontent.com/assets/1091114/20991961/08839436-bc96-11e6-808d-385fc4894a71.png">

**Comment by WorldDownTown** [comment]
@gravicle Hi, thank you for opening issue. Sorry, I had a mistake. I had updated ZoomTransitioning for CocoaPods. Please check it out.
https://cocoapods.org/pods/ZoomTransitioning

**Comment by gravicle** [comment]
Thank you for the quick fix and for the pod. Closing this!
🙌🏼
