### ISSUE TITLE
About zoomTransition from round imageView to another round ImageView

### ISSUE THREAD

**Issue by lyc2345** [WorldDownTown/ZoomTransitioning#11]
HI, I have a round image view transition to another round imageview, 
Before transition the imageView will show rectangle imageView. 
Then do the transition. 
And before finished it still a rectangle imageview then hidden.

Is any hint that I can do it with round ImageView?

Thank you very much. This Framework is awesome.

**Comment by WorldDownTown** [comment]
Thank you for requesting. I want to resolve your question. So show me how to reproduce its condition such as a sample Xcode roejct.

**Comment by WorldDownTown** [comment]
@lyc2345 Thank you for requesting. I want to resolve your question. So show me how to reproduce its condition such as a sample Xcode roejct.
