### ISSUE TITLE
iOS10, trigger system interactivePopGestureRecognizer will pop twice

### ISSUE THREAD

**Issue by winddpan** [WorldDownTown/ZoomTransitioning#16]
In the demo, I insert a UIViewController before the ImageListViewController, and I trigger the system interactivePopGestureRecognizer in ImageDetailViewController, then it poped twice, skipped the ImageListViewController.
![ss](https://user-images.githubusercontent.com/1052486/28364056-8b3823a4-6cb5-11e7-82c2-c5a99490557d.png)

**Comment by WorldDownTown** [comment]
This bug fixed in #17.
