### ISSUE TITLE
Can't go back from collectionViewController and Animation not working if the inheritance is more than 2 ViewControllers

### ISSUE THREAD

**Issue by unittesting0** [WorldDownTown/ZoomTransitioning#4]
(A)TabBarController --> (B)Navigation Controller --> (C)ViewController -> (D)TableViewController -> (E)ZoomNavigationController -> (F)CollectionViewController -> (G)DetailViewController
1. It works but I can't go back from (F) to (D) (the back button is not showing up)
2. Tabbar has been disappeared.

I have tried to Put ZoomNavigationController before (D) but the animation does not work.

**Comment by WorldDownTown** [comment]
Hi, thanks for opening the issue!
​
I have a question; Do (D)TableViewController and (F)CollectionViewController share the same navigation controller?
​
If they are not contained in the same `UINavigationController` then this behaviour is expected, and the animation is expected to fail.
​
ZoomTransitioning is coupled to `UINavigationControllerDelegate` therefore the two transitioning ViewControllers must contained in the same `UINavigationController`.

**Comment by WorldDownTown** [comment]
@unittesting0 I'm going to close this ticket. Because it has already been a week since you opened the issue.
