### ISSUE TITLE
Unable to find pod

### ISSUE THREAD

**Issue by eeallen1** [WorldDownTown/ZoomTransitioning#5]
After trying:

`pod 'ZoomTransitioning'`

I get 

`[!] Unable to find a specification for 'ZoomTransitioning'` 

on cocopaods version 1.0.1

**Comment by WorldDownTown** [comment]
Hi, thanks for opening the issue.

I also reproduced the same problem, but I tried two commands blow;

``` sh
$ pod repo remove master
$ pod setup
```

Then I succeeded `pod install`.

**Comment by eeallen1** [comment]
@WorldDownTown thanks, this also worked for me

**Comment by WorldDownTown** [comment]
@eeallen1 It's nice to work well.
