### ISSUE TITLE
Requirements iOS version

### ISSUE THREAD

**Issue by hikarut** [WorldDownTown/ZoomTransitioning#7]
Hello.

I have a question about the requirements iOS version.
Requirements version and read the README. Wrote 8.0,
But you are prompted to 9.3 or more iOS versions when you build the project.
This is the error.

```
Module file's minimum deployment target is ios9.3 v9.3: /Users/hikaru/ios/test/Carthage/Build/iOS/ZoomTransitioning.framework/Modules/ZoomTransitioning.swiftmodule/x86_64.swiftmodule
```

<img width="760" alt="2016-09-20 23 34 59" src="https://cloud.githubusercontent.com/assets/16849908/18674938/c2ee90c0-7f8b-11e6-99a2-aa37e5c203ec.png">

Also deploy version when you check here has become to 9.3.
https://github.com/WorldDownTown/ZoomTransitioning/blob/master/ZoomTransitioning.xcodeproj/project.pbxproj#L201

Is it possible to build in less than 9.3?
<img width="757" alt="2016-09-20 23 35 13" src="https://cloud.githubusercontent.com/assets/16849908/18674966/d692e93c-7f8b-11e6-8e91-891e90062a51.png">

Version of Xcode is using 7.3.1.

**Comment by WorldDownTown** [comment]
@hikarut Hi, thank you for opening the issue. You are absolutely right. I had a mistake. I'll update deployment target for iOS 8.0.

**Comment by WorldDownTown** [comment]
@hikarut I updated deployment target for iOS 8. Use v1.3.0. This version compatible for Swift 2.2 and iOS 8.0.
https://github.com/WorldDownTown/ZoomTransitioning/releases/tag/1.3.0

**Comment by hikarut** [comment]
Thank you for quick response!!

I check the version 1.3.0.
Without any problem it could be build.
Thank you again!
